# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - /core
      - /proto/gen/go
      - /tools
    schedule:
      interval: weekly
